use crate::{
    collection::RecipeId,
    template::{Template, TemplateError, TriggeredRequestError},
    util::doc_link,
};
use itertools::Itertools;
use std::{io, iter, path::PathBuf, sync::Arc};
use thiserror::Error;

/// A wrapper around [mlua::Error] that provides better introspection on the
/// `CallbackError` variant
#[derive(Debug, Error)]
pub enum LuaError {
    /// The [mlua::Error] doesn't return anything from its `source()` method,
    /// so there's no way to get at inner errors through that. This version
    /// provides full chain introspection, and also better formatting for the
    /// stack traceback.
    #[error("{traceback}")]
    Callback {
        traceback: String,
        #[source]
        source: Arc<dyn std::error::Error + Send + Sync>,
    },
    /// Any error type other than "callback"
    #[error(transparent)]
    Other(mlua::Error),
}

impl LuaError {
    /// Clean up a Lua traceback to make it more readable for the user
    fn clean_traceback(traceback: String) -> String {
        // TODO strip out useless frames
        traceback.replace('\t', "")
    }
}

impl From<mlua::Error> for LuaError {
    fn from(error: mlua::Error) -> Self {
        match error {
            mlua::Error::CallbackError { traceback, cause } => {
                let traceback = Self::clean_traceback(traceback);
                Self::Callback {
                    traceback,
                    source: cause,
                }
            }
            // Callback errors wrapped in context should also be converted
            mlua::Error::WithContext { context, cause } => {
                // We _probably_ onlt the only reference to the inner error, but
                // just to be safe we'll handle the case where we don't
                let cause = Arc::try_unwrap(cause)
                    .unwrap_or_else(|cause| mlua::Error::clone(&cause));
                Self::Other(mlua::Error::WithContext {
                    context,
                    // Convert the inner error
                    cause: mlua::Error::external(Self::from(cause)).into(),
                })
            }
            _ => Self::Other(error),
        }
    }
}

/// Any error that can occur in one of the provided Lua functions
#[derive(Debug, Error)]
pub enum FunctionError {
    /// Error executing an external command
    #[error(
        "Executing command `{}`", iter::once(program).chain(args).format(" ")
    )]
    Command {
        program: String,
        args: Vec<String>,
        #[source]
        error: io::Error,
    },

    /// An error occurred accessing the persistence database. This error is
    /// generated by our code so we don't need any extra context.
    #[error(transparent)]
    Database(anyhow::Error),

    /// Error opening/reading a file
    #[error("Reading file `{path}`")]
    File {
        path: PathBuf,
        #[source]
        error: io::Error,
    },

    /// Invalid JSONPath query
    #[error("Invalid JSONPath `{path}`")]
    JsonPathParse {
        path: String,
        #[source]
        source: serde_json_path::ParseError,
    },
    /// Got either 0 or 2+ results for JSON path query. This is generated by
    /// internal code so we don't need extra context
    #[error("Invalid JSONPath result")]
    JsonPathQuery(
        #[from]
        #[source]
        serde_json_path::ExactlyOneError,
    ),

    /// Never got a reply from the prompt channel. Do *not* store the
    /// `RecvError` here, because it provides useless extra output to the user.
    #[error("No reply from prompt/select")]
    PromptNoReply,

    /// Recipe for `response()` does not exist
    #[error("Unknown request recipe: {_0}")]
    RecipeUnknown(RecipeId),

    /// Recipe for `response()` has no history
    #[error("No response available")]
    ResponseMissing,

    /// Specified header did not exist in the response
    #[error("Header `{header}` not in response")]
    ResponseMissingHeader { header: String },

    /// Failed to parse the response body before applying JSONPath
    #[error("Parsing response")]
    ResponseParse {
        #[source]
        error: serde_json::Error,
    },

    /// Something bad happened while triggering a request dependency
    #[error("Triggering upstream recipe `{recipe_id}`")]
    Trigger {
        recipe_id: RecipeId,
        #[source]
        error: TriggeredRequestError,
    },

    /// Error rendering a nested template
    #[error("Error rendering template `{}`", template.display())]
    Template {
        template: Template,
        #[source]
        error: TemplateError,
    },

    /// Couldn't guess content type from request/file/etc. metadata
    #[error(
        "Selector cannot be applied; content type not provided and could not \
be determined from metadata. See docs for supported content types: {}",
        doc_link("api/request_collection/content_type")
    )]
    UnknownContentType,
}

impl From<FunctionError> for mlua::Error {
    fn from(error: FunctionError) -> Self {
        mlua::Error::external(error)
    }
}
