use crate::{
    collection::RecipeId, template::TriggeredRequestError, util::doc_link,
};
use itertools::Itertools;
use petit_js::error::RuntimeError;
use std::{io, iter, path::PathBuf};
use thiserror::Error;

/// Any error that can occur in one of the provided JS functions
#[derive(Debug, Error)]
pub enum FunctionError {
    /// Malformed argument
    #[error("Argument error: {0}")]
    Argument(String),

    /// Error executing an external command
    #[error(
        "Executing command `{}`", iter::once(program).chain(args).format(" ")
    )]
    Command {
        program: String,
        args: Vec<String>,
        #[source]
        error: io::Error,
    },

    /// An error occurred accessing the persistence database. This error is
    /// generated by our code so we don't need any extra context.
    #[error(transparent)]
    Database(anyhow::Error),

    /// An bubbled-up error from rendering a profile field value
    #[error("Rendering nested template for field `{field}`")]
    FieldNested {
        field: String,
        #[source]
        error: anyhow::Error,
    },

    /// Error opening/reading a file
    #[error("Reading file `{path}`")]
    File {
        path: PathBuf,
        #[source]
        error: io::Error,
    },

    /// Template context not available. Could be a bug, but it probably
    /// indicates a render function was called outside a render
    #[error(
        "Render context not available. Slumber render functions can only \
        be called during a recipe render"
    )]
    NoContext,

    /// Never got a reply from the prompt channel. Do *not* store the
    /// `RecvError` here, because it provides useless extra output to the user.
    #[error("No reply from prompt/select")]
    PromptNoReply,

    /// Recipe for `response()` does not exist
    #[error("Unknown request recipe: {_0}")]
    RecipeUnknown(RecipeId),

    /// Recipe for `response()` has no history
    #[error("No response available")]
    ResponseMissing,

    /// Specified header did not exist in the response
    #[error("Header `{header}` not in response")]
    ResponseMissingHeader { header: String },

    /// Failed to parse the response body before applying JSONPath
    #[error("Parsing response")]
    ResponseParse {
        #[source]
        error: serde_json::Error,
    },

    /// Something bad happened while triggering a request dependency
    #[error("Triggering upstream recipe `{recipe_id}`")]
    Trigger {
        recipe_id: RecipeId,
        #[source]
        error: TriggeredRequestError,
    },

    /// Couldn't guess content type from request/file/etc. metadata
    #[error(
        "Selector cannot be applied; content type not provided and could not \
        be determined from metadata. See docs for supported content types: {}",
        doc_link("api/request_collection/content_type")
    )]
    UnknownContentType,
}

impl From<FunctionError> for RuntimeError {
    fn from(error: FunctionError) -> Self {
        RuntimeError::custom(error)
    }
}
