use crate::{collection::RecipeId, render::TriggeredRequestError};
use itertools::Itertools;
use petitscript::error::RuntimeError;
use serde_json_path::JsonPath;
use std::{io, iter, path::PathBuf, sync::Arc};
use thiserror::Error;

/// Any error that can occur in a function of the `slumber` PS module
#[derive(Debug, Error)]
pub enum FunctionError {
    /// Error executing an external command
    #[error(
        "Executing command `{}`", iter::once(program).chain(args).format(" ")
    )]
    Command {
        program: String,
        args: Vec<String>,
        #[source]
        error: io::Error,
    },

    /// User passed an empty command arrary
    #[error("Command must have at least one element")]
    CommandEmpty,

    /// An error occurred accessing the persistence database. This error is
    /// generated by our code so we don't need any extra context.
    #[error(transparent)]
    Database(anyhow::Error),

    /// Error opening/reading a file
    #[error("Reading file `{path}`")]
    File {
        path: PathBuf,
        #[source]
        error: io::Error,
    },

    /// Error decoding bytes as UTF-8
    #[error(transparent)]
    InvalidUtf8(#[from] std::string::FromUtf8Error),

    /// JSONPath query returned 0 or 2+ results when we expected 1
    #[error(
        "Expected exactly one result from JSONPath query `{query}`, \
        but got {actual_count}"
    )]
    JsonPathExactlyOne {
        query: JsonPath,
        actual_count: usize,
    },

    /// JSONPath query returned no results when it should have
    #[error("No results from JSONPath query `{query}`")]
    JsonPathNoResults { query: JsonPath },

    /// Render context not available. Could be a bug, but it probably indicates
    /// a render function was called outside a render
    #[error(
        "Render context not available. Slumber render functions can only \
        be called during a recipe render. For recipe fields, make sure the \
        template string is a function: () => `My name is ${{username()}}`"
    )]
    NoContext,

    /// An bubbled-up error from rendering a profile field value
    #[error("Nested render for field `{field}`")]
    ProfileNested {
        field: String,
        /// The bubbled error. This needs an `Arc` because profile render
        /// results are cached, therefore the error must be `Clone`.
        #[source]
        error: Arc<anyhow::Error>,
    },

    /// Never got a reply from the prompt channel. Do *not* store the
    /// `RecvError` here, because it provides useless extra output to the user.
    #[error("No reply from prompt/select")]
    PromptNoReply,

    /// Recipe for `response()` has no history
    #[error("No response available")]
    ResponseMissing,

    /// Specified header did not exist in the response
    #[error("Header `{header}` not in response")]
    ResponseMissingHeader { header: String },

    /// Something bad happened while triggering a request dependency
    #[error("Triggering upstream recipe `{recipe_id}`")]
    Trigger {
        recipe_id: RecipeId,
        #[source]
        error: TriggeredRequestError,
    },
}

impl From<FunctionError> for RuntimeError {
    fn from(error: FunctionError) -> Self {
        RuntimeError::other(error)
    }
}
