//! State types for the view.

use std::time::Duration;
use uuid::Uuid;

/// A notification is an ephemeral informational message generated by some async
/// action. It doesn't grab focus, but will be useful to the user nonetheless.
/// It should be shown for a short period of time, then disappear on its own.
#[derive(Debug)]
pub struct Notification {
    /// Unique ID for this notification. Used to ensure the clear timer is
    /// clearing the correct notification
    pub id: Uuid,
    pub message: String,
}

impl Notification {
    /// Notifications should be cleared automatically after this amount of time
    pub const DURATION: Duration = Duration::from_secs(5);

    pub fn new(message: String) -> Self {
        Self {
            id: Uuid::new_v4(),
            message,
        }
    }
}
