/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_local = 1,
  anon_sym_EQ = 2,
  sym_identifier = 3,
  sym_null_ = 4,
  anon_sym_true = 5,
  anon_sym_false = 6,
  anon_sym_profile = 7,
  anon_sym_recipe = 8,
  sym_source_file = 9,
  sym_definition = 10,
  sym_local = 11,
  sym_expression = 12,
  sym_literal = 13,
  sym_bool = 14,
  sym_profile = 15,
  sym_recipe = 16,
  aux_sym_source_file_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_local] = "local",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_null_] = "null_",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_profile] = "profile",
  [anon_sym_recipe] = "recipe",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_local] = "local",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_bool] = "bool",
  [sym_profile] = "profile",
  [sym_recipe] = "recipe",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_null_] = sym_null_,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_profile] = anon_sym_profile,
  [anon_sym_recipe] = anon_sym_recipe,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_local] = sym_local,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_bool] = sym_bool,
  [sym_profile] = sym_profile,
  [sym_recipe] = sym_recipe,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_null_] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_profile] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_recipe] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_local] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_profile] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(25);
      if (lookahead == 'p') ADVANCE(21);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == 't') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 26:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_null_);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_profile);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_recipe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 26},
  [13] = {.lex_state = 26},
  [14] = {.lex_state = 26},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_null_] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_profile] = ACTIONS(1),
    [anon_sym_recipe] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym_definition] = STATE(2),
    [sym_local] = STATE(5),
    [sym_profile] = STATE(5),
    [sym_recipe] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_local] = ACTIONS(5),
    [anon_sym_profile] = ACTIONS(7),
    [anon_sym_recipe] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_local,
    ACTIONS(7), 1,
      anon_sym_profile,
    ACTIONS(9), 1,
      anon_sym_recipe,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(5), 3,
      sym_local,
      sym_profile,
      sym_recipe,
  [22] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(18), 1,
      anon_sym_profile,
    ACTIONS(21), 1,
      anon_sym_recipe,
    STATE(3), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(5), 3,
      sym_local,
      sym_profile,
      sym_recipe,
  [44] = 5,
    ACTIONS(24), 1,
      sym_null_,
    STATE(8), 1,
      sym_bool,
    STATE(10), 1,
      sym_expression,
    STATE(11), 1,
      sym_literal,
    ACTIONS(26), 2,
      anon_sym_true,
      anon_sym_false,
  [61] = 1,
    ACTIONS(28), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_profile,
      anon_sym_recipe,
  [68] = 1,
    ACTIONS(30), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_profile,
      anon_sym_recipe,
  [75] = 1,
    ACTIONS(32), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_profile,
      anon_sym_recipe,
  [82] = 1,
    ACTIONS(34), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_profile,
      anon_sym_recipe,
  [89] = 1,
    ACTIONS(36), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_profile,
      anon_sym_recipe,
  [96] = 1,
    ACTIONS(38), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_profile,
      anon_sym_recipe,
  [103] = 1,
    ACTIONS(40), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_profile,
      anon_sym_recipe,
  [110] = 1,
    ACTIONS(42), 1,
      sym_identifier,
  [114] = 1,
    ACTIONS(44), 1,
      sym_identifier,
  [118] = 1,
    ACTIONS(46), 1,
      sym_identifier,
  [122] = 1,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
  [126] = 1,
    ACTIONS(50), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 61,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 75,
  [SMALL_STATE(8)] = 82,
  [SMALL_STATE(9)] = 89,
  [SMALL_STATE(10)] = 96,
  [SMALL_STATE(11)] = 103,
  [SMALL_STATE(12)] = 110,
  [SMALL_STATE(13)] = 114,
  [SMALL_STATE(14)] = 118,
  [SMALL_STATE(15)] = 122,
  [SMALL_STATE(16)] = 126,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_profile, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local, 4, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [48] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_slumber(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "slumber",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
