use crate::{
    collection::{ProfileId, RecipeId},
    http::{RequestBuildError, RequestError},
    template::render::RenderValue,
};
use itertools::Itertools;
use std::{io, iter, path::PathBuf, string::FromUtf8Error, sync::Arc};
use thiserror::Error;

/// Any error that can occur during template rendering. The purpose of having a
/// structured error here (while the rest of the app just uses `anyhow`) is to
/// support localized error display in the UI, e.g. showing just one portion of
/// a string in red if that particular template key failed to render.
///
/// The error always holds owned data so it can be detached from the lifetime
/// of the template context. This requires a mild amount of cloning in error
/// cases, but those should be infrequent so it's fine.
///
/// These error messages are generally shown with additional parent context, so
/// they should be pretty brief.
///
/// This type implements `Clone` so it can be shared between deduplicated
/// renders.
///
/// TODO update comment
/// TODO sort variants alphabetically
#[derive(Clone, Debug, Error)]
#[cfg_attr(test, derive(PartialEq))]
pub enum RenderError {
    /// Error executing an external command
    #[error(
        "Executing command `{}`", iter::once(program).chain(args).format(" ")
    )]
    Command {
        program: String,
        args: Vec<String>,
        #[source]
        error: Arc<io::Error>,
    },

    /// An error occurred accessing the persistence database. This error is
    /// generated by our code so we don't need any extra context.
    #[error(transparent)]
    Database(Arc<anyhow::Error>),

    /// Tried to load profile data with no profile selected
    #[error("No profile selected")]
    ProfileNotSelected,

    /// Unknown profile ID
    #[error("Unknown profile `{profile_id}`")]
    ProfileUnknown { profile_id: ProfileId },

    /// A profile field key contained an unknown field
    /// TODO update to support profile or locals
    #[error("Unknown variable `{variable}`")]
    VariableUnknown { variable: String },

    /// User tried to access a global variable, which is not allowed
    #[error(
        "Unknown global variable `{variable}`. Global variables are not \
        allowed; use `locals` or `profile` instead"
    )]
    GlobalVariable { variable: String },

    /// An bubbled-up error from rendering a nested expression
    /// TODO rename or delete
    #[error("Rendering {description}")]
    Nested {
        description: String,
        #[source]
        error: Box<Self>,
    },

    /// TODO
    /// TODO can we use Display impl on this?
    #[error("Expected a single value but received: {value:?}")]
    ExpectedScalar { value: RenderValue },

    /// Error opening/reading a file
    #[error("Reading file `{path}`")]
    File {
        path: PathBuf,
        #[source]
        error: Arc<io::Error>,
    },

    /// Called a function that doesn't exist
    #[error("Unknown function `{name}`")]
    FunctionUnknown { name: String },
    /// Error deserializing function arguments
    /// TODO better message (include fn name?)
    #[error("Invalid function argument")]
    FunctionArgument {
        #[source]
        error: Arc<hcl::Error>,
    },

    /// Invalid JSONPath query
    #[error("Invalid JSONPath `{path}`")]
    JsonPathParse {
        path: String,
        #[source]
        error: Arc<serde_json_path::ParseError>,
    },
    /// No results returned from a JSONPath query that expected 1 or 1+
    #[error("No results from JSONPath query")]
    JsonPathNone,
    /// 2+ results returned from a JSONPath query that expected 1
    #[error(
        "Too many results from  JSONPath query; \
        expected 1 but got {actual_count}"
    )]
    JsonPathTooMany { actual_count: usize },

    /// In many contexts, the render output needs to be usable as a string.
    /// This error occurs when we wanted to render to a string, but whatever
    /// bytes we got were not valid UTF-8. The underlying error message is
    /// descriptive enough so we don't need to give additional context.
    #[error(transparent)]
    InvalidUtf8(FromUtf8Error),

    /// Never got a response from the prompt channel. Do *not* store the
    /// `RecvError` here, because it provides useless extra output to the user.
    #[error("No response from prompt/select")]
    PromptNoReply,

    /// Recipe for `response()` has no history
    #[error("No response available for recipe `{recipe_id}`")]
    ResponseMissing { recipe_id: RecipeId },
    /// Specified header did not exist in the response
    #[error("Header `{header}` not in response")]
    ResponseMissingHeader { header: String },
    /// Failed to parse the response body before applying JSONPath
    #[error("Parsing response")]
    ResponseParse {
        #[source]
        error: Arc<serde_json::Error>,
    },

    /// Something bad happened while triggering a request dependency
    #[error("Triggering upstream recipe `{recipe_id}`")]
    Trigger {
        recipe_id: RecipeId,
        #[source]
        error: TriggeredRequestError,
    },
}

impl RenderError {
    /// Does the given error have *any* error in its chain that contains
    /// [TriggeredRequestError::NotAllowed]? This makes it easy to attach
    /// additional error context.
    pub fn has_trigger_disabled_error(error: &anyhow::Error) -> bool {
        error.chain().any(|error| {
            matches!(
                error.downcast_ref(),
                Some(Self::Trigger {
                    error: TriggeredRequestError::NotAllowed,
                    ..
                })
            )
        })
    }
}

pub trait RenderResultExt {
    /// TODO
    fn context(self, description: impl ToString) -> Self;
}

impl<T> RenderResultExt for Result<T, RenderError> {
    fn context(self, description: impl ToString) -> Self {
        self.map_err(|error| RenderError::Nested {
            description: description.to_string(),
            error: Box::new(error),
        })
    }
}

/// Error occurred while trying to build/execute a triggered request.
///
/// This type implements `Clone` so it can be shared between deduplicated chain
/// renders, hence the `Arc`s on inner errors.
#[derive(Clone, Debug, Error)]
#[cfg_attr(test, derive(PartialEq))]
pub enum TriggeredRequestError {
    /// This render was invoked in a way that doesn't support automatic request
    /// execution. In some cases the user needs to explicitly opt in to enable
    /// it (e.g. with a CLI flag)
    #[error("Triggered request execution not allowed in this context")]
    NotAllowed,

    /// Tried to auto-execute a chained request but couldn't build it
    #[error(transparent)]
    Build(#[from] Arc<RequestBuildError>),

    /// Chained request was triggered, sent and failed
    #[error(transparent)]
    Send(#[from] Arc<RequestError>),
}
