[book]
authors = ["Lucas Pickering"]
description = "Terminal-based HTTP client"
language = "en"
multilingual = false
src = "src"
title = "Slumber"

[preprocessor.pagetoc]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
edit-url-template = "https://github.com/LucasPickering/slumber/edit/master/docs/{path}"
git-repository-url = "https://github.com/LucasPickering/slumber"
