[book]
authors = ["Lucas Pickering"]
description = "Slumber is a TUI (terminal user interface) HTTP client. Define, execute, and share configurable HTTP requests."
language = "en"
multilingual = false
src = "src"
title = "Slumber"

[preprocessor.pagetoc]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
default-theme = "dark"
edit-url-template = "https://github.com/LucasPickering/slumber/edit/master/docs/{path}"
git-repository-url = "https://github.com/LucasPickering/slumber"
preferred-dark-theme = "coal"

[output.html.redirect]
# Every page linked in the old oranda+mdbook world needs a redirect here. Sadly
# mdbook doesn't support blanket redirects :(
"/book/api/configuration/editor.html" = "/user_guide/tui/editor.html"
"/book/api/configuration/index.html" = "/api/configuration/index.html"
"/book/api/configuration/input_bindings.html" = "/api/configuration/input_bindings.html"
"/book/api/configuration/mime.html" = "/api/configuration/mime.html"
"/book/api/configuration/theme.html" = "/api/configuration/theme.html"
"/book/api/request_collection/chain.html" = "/api/request_collection/chain.html"
"/book/api/request_collection/chain_source.html" = "/api/request_collection/chain_source.html"
"/book/api/request_collection/content_type.html" = "/api/request_collection/content_type.html"
"/book/api/request_collection/index.html" = "/api/request_collection/index.html"
"/book/api/request_collection/profile.html" = "/api/request_collection/profile.html"
"/book/api/request_collection/recipe_body.html" = "/api/request_collection/recipe_body.html"
"/book/api/request_collection/request_recipe.html" = "/api/request_collection/request_recipe.html"
"/book/api/request_collection/template.html" = "/api/request_collection/template.html"
"/book/troubleshooting/shell_completions.html" = "/install.html#shell-completions"
"/book/user_guide/database.html" = "/user_guide/database.html"
"/book/user_guide/tui/editor.html" = "/user_guide/tui/editor.html"
"/book/user_guide/tui/filter_query.md" = "/user_guide/tui/filter_query.md"
